# Challenge 8

In [58]:
import numpy as np
import pandas as pd

from sklearn import tree
from sklearn.model_selection import train_test_split
import pydotplus

from sklearn import metrics

## 8.1 Decision Tree Classifier

In [12]:
df = pd.read_csv('house-votes-84.data.txt', names = ['party', 'x1','x2','x3','x4','x5','x6','x7','x8','x9','x10','x11',
                                                    'x12','x13','x14','x15','x16'])

In [13]:
# clean up data

df.replace('n',0, inplace=True)
df.replace('y',1, inplace=True)

In [14]:
means=[]
for i in xrange(16):
    means.append((df[df['x%s' %(i+1)]!='?'].iloc[:,i+1].mean()))
    
# replace ? by 0/1 with p = mean
def replace_no(x):
    if x == '?':
        x = np.random.binomial(1,means[i])
    return x

for i in xrange(16):
    df.iloc[:,i+1]=df.iloc[:,i+1].map(replace_no)

In [15]:
X=df.iloc[:,1:]
y=df.iloc[:,0]
tr = tree.DecisionTreeClassifier()

In [16]:
# Fit model


tr.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [17]:
# plot tree

dot_data = tree.export_graphviz(tr, out_file=None) 
graph = pydotplus.graph_from_dot_data(dot_data) 
graph.write_pdf("party.pdf")

True

## 8.2 Titanic kaggle decision tree

In [66]:
df_train = pd.read_csv('train.csv')

In [70]:
# clean data
df_train.drop(['Cabin','Ticket','Name','Embarked','PassengerId'], axis=1, inplace=True) # not usefull/ too many Nans
df_train.dropna(how='any', inplace=True)

In [71]:
df_train.replace('male',1, inplace=True)
df_train.replace('female',0, inplace=True)

In [72]:
X = df_train.drop(["Survived"], axis=1)
y = df_train["Survived"]

In [73]:
tit_tr=tree.DecisionTreeClassifier()
tit_tr.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [74]:
dot_data2 = tree.export_graphviz(tit_tr, out_file=None) 
graph = pydotplus.graph_from_dot_data(dot_data2) 
graph.write_pdf("survival.pdf")

True

In [75]:
X

     Pclass  Sex   Age  SibSp  Parch      Fare
0         3    1  22.0      1      0    7.2500
1         1    0  38.0      1      0   71.2833
2         3    0  26.0      0      0    7.9250
3         1    0  35.0      1      0   53.1000
4         3    1  35.0      0      0    8.0500
6         1    1  54.0      0      0   51.8625
7         3    1   2.0      3      1   21.0750
8         3    0  27.0      0      2   11.1333
9         2    0  14.0      1      0   30.0708
10        3    0   4.0      1      1   16.7000
11        1    0  58.0      0      0   26.5500
12        3    1  20.0      0      0    8.0500
13        3    1  39.0      1      5   31.2750
14        3    0  14.0      0      0    7.8542
15        2    0  55.0      0      0   16.0000
16        3    1   2.0      4      1   29.1250
18        3    0  31.0      1      0   18.0000
20        2    1  35.0      0      0   26.0000
21        2    1  34.0      0      0   13.0000
22        3    0  15.0      0      0    8.0292
23        1    1  28.0      0      0   35.5000
24        3    0   8.0      3      1   21.0750
25        3    0  38.0      1      5   31.3875
27        1    1  19.0      3      2  263.0000
30        1    1  40.0      0      0   27.7208
33        2    1  66.0      0      0   10.5000
34        1    1  28.0      1      0   82.1708
35        1    1  42.0      1      0   52.0000
37        3    1  21.0      0      0    8.0500
38        3    0  18.0      2      0   18.0000
..      ...  ...   ...    ...    ...       ...
856       1    0  45.0      1      1  164.8667
857       1    1  51.0      0      0   26.5500
858       3    0  24.0      0      3   19.2583
860       3    1  41.0      2      0   14.1083
861       2    1  21.0      1      0   11.5000
862       1    0  48.0      0      0   25.9292
864       2    1  24.0      0      0   13.0000
865       2    0  42.0      0      0   13.0000
866       2    0  27.0      1      0   13.8583
867       1    1  31.0      0      0   50.4958
869       3    1   4.0      1      1   11.1333
870       3    1  26.0      0      0    7.8958
871       1    0  47.0      1      1   52.5542
872       1    1  33.0      0      0    5.0000
873       3    1  47.0      0      0    9.0000
874       2    0  28.0      1      0   24.0000
875       3    0  15.0      0      0    7.2250
876       3    1  20.0      0      0    9.8458
877       3    1  19.0      0      0    7.8958
879       1    0  56.0      0      1   83.1583
880       2    0  25.0      0      1   26.0000
881       3    1  33.0      0      0    7.8958
882       3    0  22.0      0      0   10.5167
883       2    1  28.0      0      0   10.5000
884       3    1  25.0      0      0    7.0500
885       3    0  39.0      0      5   29.1250
886       2    1  27.0      0      0   13.0000
887       1    0  19.0      0      0   30.0000
889       1    1  26.0      0      0   30.0000
890       3    1  32.0      0      0    7.7500

[714 rows x 6 columns]